[tools]
"mdbook" = "latest"
"ubi:badboy/mdbook-mermaid" = "latest"
"ubi:badboy/mdbook-toc" = "latest"
"ubi:lzanini/mdbook-katex" = "0.9.2-binaries"
"ubi:tommilligan/mdbook-admonish" = "latest"
"ubi:jonahgoldwastaken/mdbook-external-links" = "latest"
"ubi:ivaaaan/smug" = "latest"
